# Generated by Django 5.1 on 2024-10-01 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_rename_post_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='message.messages'),
        ),
    ]
