# Generated by Django 5.1 on 2024-09-17 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('name', models.CharField(blank=True, max_length=200, unique=True)),
                ('surname', models.CharField(blank=True, max_length=200, unique=True)),
                ('profile_pic', models.CharField(blank=True, max_length=200)),
                ('countries_visited', models.CharField(blank=True, max_length=200)),
                ('interests', models.CharField(blank=True, max_length=200)),
                ('nationality', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
