# Generated by Django 5.1 on 2024-09-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='countries_visited',
            field=models.CharField(blank=True, default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='interests',
            field=models.CharField(blank=True, default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='profile_picurl',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=200, unique=True),
        ),
    ]
