# Generated by Django 5.1 on 2024-09-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_myprofile_countries_visited_myprofile_interests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='countries_visited',
            field=models.CharField(blank=True, default='How many?!', max_length=200),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='interests',
            field=models.CharField(blank=True, default='Do you have any?', max_length=200),
        ),
    ]
