# Generated by Django 5.1 on 2024-09-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_alter_myprofile_countries_visited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='countries_visited',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='interests',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='name',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='surname',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
