# Generated by Django 5.1 on 2024-09-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0004_alter_myprofile_countries_visited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
