# Generated by Django 5.1 on 2024-09-17 17:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_img',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image'),
        ),
    ]
