# Generated by Django 5.1 on 2024-09-17 17:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
